name: ArenaFutbol
main: me.morrango.arenafutbol.ArenaFutbol
version: 0.5.4
website: http://
author: Morrango
depend: [BattleArena]

description: >
             version 2 of futbol
commands:
  futbol:
    description: arena futbol
    aliases: [fb]
    usage: |
           /fb <ball|balltimer|pitch|maxpitch|power>
